### ISSUE TITLE
The check of validationQuerySQL has logic problem[class:BeeDataSourceConfig, method:check], 313 line.

### ISSUE THREAD

**Issue by myhubxxx** [Chris2018998/BeeCP#1]
check the validationQuerySQL, may be you can change to this.
`if (this.validationQuerySQL != null) {
	if ( ! this.validationQuerySQL.toLowerCase().trim().startsWith("select "))
		throw new IllegalArgumentException("connection calidate SQL must start with 'select '");
        }`

**Comment by Chris2018998** [comment]
fixed
