### ISSUE TITLE
存在物理连接直接暴露的问题

### ISSUE THREAD

**Issue by JoyceLikeRose** [Chris2018998/BeeCP#11]
上次阅读光连接池代码，发现这个问题，您的池同样有这样的问题。

地址：https://github.com/brettwooldridge/HikariCP/issues/1444

中国开源社区在搞投票活动，您的作品参与了码？ 帮您投票去

**Comment by Chris2018998** [comment]
好的，我检查一下代码。

活动挺好的，个人作品有点简陋，即便参与，被瞧上的几率也很低。

**Comment by Chris2018998** [comment]
Fixed. 可以再验证一下，看看是否还有问题
