### ISSUE TITLE
大牛牛，太牛啦；支持你

### ISSUE THREAD

**Issue by skyformat99** [Chris2018998/BeeCP#13]
开发最好最快的连接池；
超越hikari哈哈
😄

**Comment by Chris2018998** [comment]
哈哈，不敢当，感谢您支持。😁

**Comment by Chris2018998** [comment]
您能帮忙审阅一下代码吗? 帮忙看看什么地方存在错误或还可以继续改进的.

**Comment by yjc2020** [comment]
不支持jdk8吗？

**Comment by Chris2018998** [comment]
对不起，才注意到您的提问。麻烦以后开新的issue, 避免被忽略。

支持java8可以的，maven版本上描述java6,java7是说这个版本用java6或Java7编译打包的。
