### ISSUE TITLE
请问networkTimeout是做什么的？有个警告日志

### ISSUE THREAD

**Issue by crazyliuzc** [Chris2018998/BeeCP#16]
[2020-08-05 18:55:41,444][WARN][cn.beecp.pool.FastConnectionPool.setDefaultOnRawConn(FastConnectionPool.java:324)]: 
 BeeCP(FastPool-1)driver not support 'networkTimeout'

**Comment by Chris2018998** [comment]
networkTimeout 是一个网络超时控制时间,表达的意思是:从驱动端发起的请求,多少时间内能获得数据服务端的响应.

它的时间单位是毫秒,若值等于0,则表示永不超时.

那个警告原本意思是说驱动不支持networkTimeout ,实际上是    **池中有个Bug.**  应该排除0,下一个版本将会修复.
