### ISSUE TITLE
请问sql日志怎么打印？如何添加Log4j2？

### ISSUE THREAD

**Issue by crazyliuzc** [Chris2018998/BeeCP#17]

**Comment by Chris2018998** [comment]
1： 目前没有提供执行SQL语句打印，您可以使用其他一些监控工具，比如 P6Spy。

2：连接池内部使用的是SLF4J打印日志的，可以在应用端增加Log4j2的一些配置就可以了。
     给一个参考：https://my.oschina.net/u/131191/blog/819593
