### ISSUE TITLE
There are a problem in class#PooledConnectionArray method#allAll

### ISSUE THREAD

**Issue by myhubxxx** [Chris2018998/BeeCP#2]
`System.arraycopy(arrayOld,0,arrayNew,0,oldLen);
System.arraycopy(arrayAdd,0,arrayNew,0,addLen);`
can be 
`System.arraycopy(arrayOld,0,arrayNew,0,oldLen);
System.arraycopy(arrayAdd,0,arrayNew,oldLen,addLen);`

**Comment by Chris2018998** [comment]
Thanks, I fixed it.
