### ISSUE TITLE
严重BUG ：spring cloud下启动失败

### ISSUE THREAD

**Issue by ChinaLym** [Chris2018998/BeeCP#20]
背景：在 [shoulder-platform](https://github.com/ChinaLym/shoulder-platform) 中尝试将 beeCP作为连接池技术选型，中遇到了以下问题。
**根本原因**：设计问题，BeeCPDataSource `close` 时可能抛异常
直接原因：spring cloud 启动时会加载两次上下文，在切换上下文时，会关闭第一次加载中的dataSource，但此时还未初始化，BeeCP close 抛出异常，导致应用无法启动。

**解决方案**：可以参考 Durid 或者 HikairCP，如果未启动，仅记录日志。

复现参考：[shoulder-platform](https://github.com/ChinaLym/shoulder-platform](shoulder-platform](https://github.com/ChinaLym/shoulder-platform) sms短信中心

**Comment by Chris2018998** [comment]
正式包已经发出.
