### ISSUE TITLE
web 界面的监控能不能丰富些啊 至少显示监控慢sql嘛

### ISSUE THREAD

**Issue by liangbaika** [Chris2018998/BeeCP#26]
web 界面的监控能不能丰富些啊 至少显示监控慢sql嘛   监控也挺重要的 严格来说虽然不属于连接池的功能

**Comment by Chris2018998** [comment]
好的，马上安排.

**Comment by Chris2018998** [comment]
真诚向您道个歉，原来计划安排加个SQL执行监控，由于最近状态有点疲劳，都忘记了。

快开发好了，过几天应该可以发布了。

**Comment by liangbaika** [comment]
辛苦了  打算后面的新项目用这个连接池试一试------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;欧德&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月26日(星期六) 晚上8:26
收件人:&nbsp;&quot;Chris2018998/BeeCP&quot;<BeeCP@noreply.github.com&gt;;
抄送:&nbsp;&quot;凉白开&quot;<1144388620@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Chris2018998/BeeCP] web 界面的监控能不能丰富些啊 至少显示监控慢sql嘛 (#26)

**Comment by Chris2018998** [comment]
大致效果图

![image](https://user-images.githubusercontent.com/32663325/103155789-c1d15c80-47dd-11eb-8b4c-afefc058ec75.png)

**Comment by Chris2018998** [comment]
Github上有的图看不到了，可以访问

https://my.oschina.net/u/3918073/blog/4843187

**Comment by liangbaika** [comment]
可以的  小建议  时间字段支持排序 是否成功也支持排序 失败的高亮显示 执行时间过长的也高亮------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;欧德&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月27日(星期天) 凌晨0:52
收件人:&nbsp;&quot;Chris2018998/BeeCP&quot;<BeeCP@noreply.github.com&gt;;
抄送:&nbsp;&quot;凉白开&quot;<1144388620@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Chris2018998/BeeCP] web 界面的监控能不能丰富些啊 至少显示监控慢sql嘛 (#26)

**Comment by Chris2018998** [comment]
感谢回复，好的，我再优化一下。

**Comment by Chris2018998** [comment]
1：SQL监控前端界面支持分页，排序，时间过长高亮展示:
2：SQL监控后端支持警告类嵌入，用于推送执行时间过长的SQL列表，可编写通知逻辑

```
<dependency>
   <groupId>com.github.chris2018998</groupId>
   <artifactId>beecp-spring-boot-starter</artifactId>
   <version>1.4.0</version>
</dependency>
```

界面信息请访问：
https://my.oschina.net/u/3918073/blog/4874167
