### ISSUE TITLE
建议增加时序数据库的

### ISSUE THREAD

**Issue by skyformat99** [Chris2018998/BeeCP#28]
比如 infuxdb

taosdb    
https://www.taosdata.com/cn/

**Comment by Chris2018998** [comment]
好的。感谢您的建议。做完当前这版本，下一版本就着手。

**Comment by Chris2018998** [comment]
1： taosdb 数据库有JDBC驱动实现，可以用BeeCP支持它
2： infuxdb，个人打算利用对象池(BeeOP)去支持它，等0.5版本出来后，再制作一个infuxdb-demo

**Comment by Chris2018998** [comment]
Influxdb例子代码
https://github.com/Chris2018998/BeeOP/blob/main/doc/example/BeeOP-Influxdb.zip

**Comment by skyformat99** [comment]
牛牛牛
