### ISSUE TITLE
能考虑一下国内用户的感受吗？

### ISSUE THREAD

**Issue by lqixv** [Chris2018998/BeeCP#31]
![bcp-2](https://user-images.githubusercontent.com/2187137/107877904-2d949380-6f0a-11eb-9128-24e726634615.png)

**Comment by lqixv** [comment]
![bcp-3](https://user-images.githubusercontent.com/2187137/107877956-79473d00-6f0a-11eb-8767-7c4b1e1fc72f.png)

**Comment by Chris2018998** [comment]
首先给您拜个年，祝您新年快乐, 牛年大吉。

下载速度慢话，我一般使用下面的方法解决

1：在hosts文件(C:\Windows\System32\drivers\etc\hosts)中增加IP映射,比如个人如下

199.232.96.133    user-images.githubusercontent.com
199.232.96.133    raw.githubusercontent.com
185.199.109.154   github.githubassets.com
199.232.96.133    gist.githubusercontent.com
199.232.96.133    cloud.githubusercontent.com
199.232.96.133    camo.githubusercontent.com
199.232.96.133    avatars0.githubusercontent.com
199.232.96.133    avatars1.githubusercontent.com

2：这个项目在国内也有相应地址：**https://gitee.com/mirrors/BeeCP** 每天都会与github同步一次，可以试试从这个地址下载

3：使用手机热点分享给笔记本电脑，下载速度应该会好一些

4：更换宽带网络或升级网络带宽

一般早上（8点前）下载和上传得速度应该会好一些

**Comment by lqixv** [comment]
您太客气了，惭愧。
期望能在gitee上同步更新。gitee并没能做到如其说的那样每天更新。如果可以，还是希望您能更新一下。
昨天我给您发消息时，仍然是前天的版本。

**Comment by lqixv** [comment]
> 首先给您拜个年，祝您新年快乐, 牛年大吉。
> 
> 个人有时下载速度也慢，一般使用下面的方法解决(仅供参考）
> 
> 1：在hosts文件(C:\Windows\System32\drivers\etc\hosts)中增加IP映射,比如个人如下
> 
> 199.232.96.133 user-images.githubusercontent.com
> 199.232.96.133 raw.githubusercontent.com
> 185.199.109.154 github.githubassets.com
> 199.232.96.133 gist.githubusercontent.com
> 199.232.96.133 cloud.githubusercontent.com
> 199.232.96.133 camo.githubusercontent.com
> 199.232.96.133 avatars0.githubusercontent.com
> 199.232.96.133 avatars1.githubusercontent.com
> 
> 2：这个项目在国内也有相应地址：**https://gitee.com/mirrors/BeeCP** 每天都会与github同步一次，可以试试从这个地址下载
> 
> 3：使用手机热点分享给笔记本电脑，下载速度应该会好一些
> 
> 4：更换宽带网络或升级网络带宽
> 
> 一般早上（8点前）下载和上传得速度应该会好一些

好用，配置后，结果如下：
![bcp-5](https://user-images.githubusercontent.com/2187137/107915218-0fc53e00-6f9f-11eb-8983-0c54de45fbb7.png)
