### ISSUE TITLE
支持h2  sqlite等常见的嵌入式数据库么

### ISSUE THREAD

**Issue by liangbaika** [Chris2018998/BeeCP#36]
支持h2  sqlite等常见的嵌入式数据库么

**Comment by Chris2018998** [comment]
h2，sqlite数据库提供了JDBC驱动，理论上来说，应该是可以的。

**Comment by Chris2018998** [comment]
过段时间对h2 sqlite具体测试一次看看。

**Comment by Chris2018998** [comment]
做个简单的测试看看

1：H2启动后的查询界面
![image](https://user-images.githubusercontent.com/32663325/110244341-3e7c7600-7f99-11eb-9d6a-86b0d31d8285.png)

2：测试代码
![image](https://user-images.githubusercontent.com/32663325/110244388-72579b80-7f99-11eb-8ac0-cc8103f11733.png)

3：执行结果
![image](https://user-images.githubusercontent.com/32663325/110244450-ab900b80-7f99-11eb-9820-afaead75aabb.png)

**Comment by Chris2018998** [comment]
sqlite 我后续补充一个测试结果

**Comment by Chris2018998** [comment]
sqlite 测试例子

1：数据服务端启动

![image](https://user-images.githubusercontent.com/32663325/110246932-a1bfd580-7fa4-11eb-84b3-db7e9155b63e.png)

2：测试代码
![image](https://user-images.githubusercontent.com/32663325/110246961-c025d100-7fa4-11eb-9ed4-a48e5f4d335b.png)

3：测试结果
![image](https://user-images.githubusercontent.com/32663325/110246982-d469ce00-7fa4-11eb-9b30-726c4357d57c.png)

不过 sqlite在设置默认事务等级有点问题，我查查

**Comment by Chris2018998** [comment]
![image](https://user-images.githubusercontent.com/32663325/110247135-a5079100-7fa5-11eb-8c72-1d78274cb8b9.png)

int TRANSACTION_READ_COMMITTED   = 2 事务等级不支持
