### ISSUE TITLE
不好意思，可以请教个问题吗？ 

### ISSUE THREAD

**Issue by WangChangJuan** [Chris2018998/BeeCP#4]
您好，Java世界中已经有一些性能非常不错的连接池了，为什么还您开发此新连接池呢？ 是想超越光连接池吗？

**Comment by Chris2018998** [comment]
感谢您的提问，开发这个连接池的主要目的
1：学习锻炼，尝试以少量的代码实现一个简单版的连接池。
2：希望有网友能帮忙检查一下代码，发现问题或提出更好提高性能方法。

开发此连接池，没有在其他网站发帖宣传，不想被误解成炫耀或挑衅（几行代码不值得炫耀，中国牛人满地是，本人菜鸟一个）。
公布跑分情况（100%是机器跑出来),  想借各位网友们的慧眼看一下，看一下这个实现方式是否可行， 有无再改进的可能性。 真诚希望得到帮忙，谢谢。

如果它有用的话，也希望它可以帮到有需要的人。

**Comment by WangChangJuan** [comment]
谢谢回帖，其实在几年前在Github上下载过您的Jmin项目代码,感觉您代码质量很不错，可不知为啥后来项目被删除了？

**Comment by WangChangJuan** [comment]
您的这个性能测试与光连接池的性能测试，有什么区别啊？这个测试结果会不会有点虚高啊？
从测试结果看，Druid与其他连接池差距有点大啊。

**Comment by Chris2018998** [comment]
几年前？不会吧。 是在我这个的账户下吗？如果不是的话，那应该是以前一起学习的群友建的吧，12

年我停止(放弃)项目的开发，后面群友可能还在继续活动吧。如果有人需要的话，我可以将代码上传到

GitHub（可能不是最新的，不清楚后面是否有其他人修改）。

**Comment by Chris2018998** [comment]
光连接池的测的应该是微性能的流量测试。

这个叫压力测试，测试连接池在多线程访问反应情况,微性能工具应该可以做类似测试，个人没有去研究.

Druid配置的参数可能不对，导致其性能未能100%发挥，它应该至少会是比Tomcat高

**Comment by Chris2018998** [comment]
关贴了，如果您还有别的问题，请开新的Issue.
