### ISSUE TITLE
能提供一些通用配置吗？

### ISSUE THREAD

**Issue by xinwu-yang** [Chris2018998/BeeCP#44]
比如针对使用MySQL那些配置可能是最佳配置，针对Oracle那些配置是最佳配置！

**Comment by Chris2018998** [comment]
好的，过段时间整理一下，最近太忙了。

**Comment by Chris2018998** [comment]
这里有一些优化性配置说明
https://my.oschina.net/u/3918073/blog/4678680

**Comment by xinwu-yang** [comment]
谢谢!
