### ISSUE TITLE
请问如何理解连接池的lastActivyTime? 

### ISSUE THREAD

**Issue by WangChangJuan** [Chris2018998/BeeCP#5]

**Comment by Chris2018998** [comment]
很高兴看到您的再次提问，我的理解如下（可能不准确）

它表示使用者对池中的连接最近一次**有效的**访问时刻点，通常是毫秒，它是作为下一次被池用于测试连接是否存活性（换句话说，即上一次访问时上有效的（活的），在指定时间范围内无须对连接进行存活再验证。）

ResultSet  Statement   Connection  三层对象之间存在依属关系，这三个对象之上任何访问都应该
属于间接或直接归于连接上。 有效性的解释： 必须是访问三个对象的方法访问后，无异常则记录操作时刻点，（有异常不一定无效，有可能SQL语句有问题，但是有一种异常则是无效的，网络异常，连接失效）考虑JDBC的驱动的差异性，比如有的断网后，可能是抛出无效连接异常，有的会报一个SQLException,异常消息提示网络异常了，但是它们都是SQLException 或其子类。

在蜜蜂连接池中统一，简化思路：异常下不记录操作时刻点（因为驱动差异性，不好识别它是语句异常，还是网络异常）。


希望以上解答能对您有所帮助，谢谢。

**Comment by WangChangJuan** [comment]
目前发现Druid只是在执行SQL的地方记时，光连接池也是如此，其他调用不计时，那岂不是时间点记录不准确？

**Comment by Chris2018998** [comment]
理论上来说调用一次都应该要记录一次时间,无论是Connection,Statement,ResultSet.
但是如果在所有方法调用加上这个时间更新，时间点是准确了，但是在高并发下，多个线程在多处都读取时间，对性能肯定有影响,。Connection主要的作用就是用来执行SQL的，记录关键操作时刻是有道理的。个人没有阅读两位大师的作品，不清楚他们是如何考虑的。具体您可以去他们的论坛直接发帖问问。

**Comment by Chris2018998** [comment]
其实做一个测试，多个线程读取System.currentTimeMillis() ,比如100个线程各自读取100次，和单个线程读取10000次对比一下总耗时间。

**Comment by WangChangJuan** [comment]
发了帖没有回应，隔壁的程序，又长又臭，看起来好费劲，居然有那么多人给星星。
中国超越国外同类产品，少之又少，中国很多东西都是假大空，一个字：吹
但您这个作品绝对算得上硬货啊，真的，一点也不夸张。
好的作品要好好宣传一下，让它发光发亮。

**Comment by Chris2018998** [comment]
谢谢肯定。好不好无所谓，我是努力做给自己看的，能进步就好。 个人不善言辞，不想做一些无聊的炒作。
