### ISSUE TITLE
请问数据库连接池的有什么局限性吗？ 

### ISSUE THREAD

**Issue by JoyceLikeRose** [Chris2018998/BeeCP#7]
今天是中秋节，首先祝您节日快乐，感谢您贡献一个高性能的连接池，它的性能确实非常棒，代码质量也很优秀，国产的骄傲！

我这里有个疑问，请您帮忙解答：当今分布式开发为主流背景下，连接池有什么局限性吗？ 以及如何改变呢？

**Comment by JoyceLikeRose** [comment]
谢谢回复，期待您的下一个作品。

**Comment by JoyceLikeRose** [comment]
谢谢回复，很富有创意的想法，期待您的下一个作品。

**Comment by Chris2018998** [comment]
请勿转贴，谢谢
