### ISSUE TITLE
贡献开源项目能挣钱吗？ 好郁闷！

### ISSUE THREAD

**Issue by JoyceLikeRose** [Chris2018998/BeeCP#8]
贡献了开源项目，却告诉我没有回报啊。靠！

**Comment by Chris2018998** [comment]
年轻人，不用激动。^_^

让一个老人来告诉你：开源是不挣钱的或者说很少挣到钱的，挣点人气或影响力而已。
惠民项目或叫互联网项目是能挣钱的，靠的是人多力量大来挣钱的。
一般优秀的项目很多都是靠超级耐力和时间堆出来的，一般个人或小组织在无法盈利下很难持久的。

我当年也曾想：努力再努力，要是挣钱到钱，就支持一下开源项目（都是苦逼的兄弟），哈哈，主要是没那实力啊。后来没办法，人累了，老了，不搞了，谁牛谁来折腾。

曾经有朋友和我开个玩笑说“靠开源挣钱不如去买股票，股票起码有5%能挣钱”   "某些人想通过开源挣钱，结果挣了个光头"。

笑一笑，十年少。开源只能玩玩，别太认真，小心烧坏脑。

**Comment by Chris2018998** [comment]
年轻人，不用激动。^_^

让一个老人来告诉你：开源是不挣钱的或者说很少挣到钱的，挣点人气或影响力而已。
惠民项目或叫互联网项目是能挣钱的，靠的是人多力量大来挣钱的。
一般优秀的项目很多都是靠超级耐力和时间堆出来的，一般个人或小组织在无法盈利下很难持久的。

我当年也曾想：努力再努力，要是挣钱到钱，就支持一下开源项目（都是苦逼的兄弟），哈哈，主要是没那实力啊。后来没办法，人累了，老了，不搞了，谁牛谁来折腾。

曾经有朋友和我开个玩笑说“靠开源挣钱不如去买股票，股票起码有5%能挣钱”   "某些人想通过开源挣钱，结果挣了个光头"。

笑一笑，十年少。开源只能玩玩，别太认真，小心烧坏脑。

**Comment by Chris2018998** [comment]
年轻人，不用激动。^_^

让一个老人来告诉你：开源是不挣钱的或者说很少挣到钱的，挣点人气或影响力而已。
惠民项目或叫互联网项目是能挣钱的，靠的是人多力量大来挣钱的。
一般优秀的项目很多都是靠超级耐力和时间堆出来的，一般个人或小组织在无法盈利下很难持久的。

我当年也曾想：努力再努力，要是挣钱到钱，就支持一下开源项目（都是苦逼的兄弟），哈哈，主要是没那实力啊。后来没办法，人累了，老了，不搞了，谁牛谁来折腾。

曾经有朋友和我开个玩笑说“靠开源挣钱不如去买股票，股票起码有5%能挣钱”   "某些人想通过开源挣钱，结果挣了个光头"。

笑一笑，十年少。开源只能玩玩，别太认真，小心烧坏脑。

**Comment by Chris2018998** [comment]
年轻人，不要激动。^_^

让一个老人来告诉你：开源是不挣钱的或者说很少挣到钱的，挣点人气或影响力而已。
惠民项目或叫互联网项目是能挣钱的，靠的是人多力量大来挣钱的。
一般优秀的项目很多都是靠超级耐力和时间堆出来的，一般个人或小组织在无法盈利下很难持久的。

曾经有朋友和我开个玩笑说“靠开源挣钱不如去买股票，股票起码有5%能挣钱” "某些人想通过开源挣钱，结果挣了个光头"。

笑一笑，十年少。开源只能玩玩，别太认真，小心烧坏脑。

**Comment by Chris2018998** [comment]
年轻人，不要激动。^_^

让一个老人来告诉你：开源是不挣钱的或者说很少挣到钱的，挣点人气或影响力而已。
惠民项目或叫互联网项目是能挣钱的，靠的是人多力量大来挣钱的。
一般优秀的项目很多都是靠超级耐力和时间堆出来的，一般个人或小组织在无法盈利下很难持久的。

曾经有朋友开个玩笑说  “靠开源挣钱不如去买股票，股票起码有5%能挣钱”    "有些人想通过开源挣钱，结果挣了个光头"。

笑一笑，十年少。开源只能玩玩，别太认真，小心烧坏脑。

**Comment by Chris2018998** [comment]
年轻人，不要激动。^_^

让一个老人来告诉你：开源是不挣钱的或者说很少挣到钱的，挣点人气或影响力而已。
惠民项目或叫互联网项目是能挣钱的，靠的是人多力量大来挣钱的。
一般优秀的项目很多都是靠超级耐力和时间堆出来的，一般个人或小组织在无法盈利下很难持久的。

曾经有朋友开个玩笑说 “靠开源挣钱不如去买股票，股票起码有5%能挣钱” "有些人想通过开源挣钱，结果挣了个光头"。

笑一笑，十年少。开源只能玩玩，别太认真，小心烧坏脑。

**Comment by JoyceLikeRose** [comment]
平衡一点了。谢谢回复。
